"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type R={sr:string,amount:number,doc:string|null,credit:number,pay:string|null};
const money=(n:number)=>"₹"+Math.round(n).toLocaleString("en-IN");
const fmt=(d:Date|null)=>d?d.toLocaleDateString("en-IN"):"—";

export default function Clause22(){
 const [data,setData]=useState<R[]>([]);
 useEffect(()=>{setData(JSON.parse(localStorage.getItem("msmeRows")||"[]"));},[]);
 const items=useMemo(()=>data.map(r=>{const doc=r.doc?new Date(r.doc):null;const pay=r.pay?new Date(r.pay):null;const due=doc?new Date(doc.getTime()+r.credit*86400000):null;const delay=due&&pay?Math.max(0,Math.round((pay.getTime()-due.getTime())/86400000)):due?Math.max(0,Math.round((new Date("2026-03-31").getTime()-due.getTime())/86400000)):0;return {...r,payDate:pay,dueDate:due,delay,within:!!pay&&delay===0};}),[data]);
 const required=items.reduce((s,x)=>s+Math.abs(x.amount),0);const paid=items.filter(x=>x.within).reduce((s,x)=>s+Math.abs(x.amount),0);const notPaid=items.filter(x=>!x.within).reduce((s,x)=>s+Math.abs(x.amount),0);const interest=items.reduce((s,x)=>s+Math.abs(x.amount)*0.15*x.delay/365,0);
 return <><header className="topbar"><div><div className="topTitle">Clause 22 Report</div><div className="topSub">Four disclosure figures with entry-level support</div></div><div className="actions"><Link href="/disallowed" className="btn btnSoft">Disallowed Entries</Link></div></header><section className="grid"><div className="stat"><div className="statLabel">22(i) Interest inadmissible u/s 23</div><div className="statValue">{money(interest)}</div></div><div className="stat"><div className="statLabel">22(ii) Amount required to be paid</div><div className="statValue">{money(required)}</div></div><div className="stat"><div className="statLabel">22(iii)(a) Paid within Section 15 time</div><div className="statValue">{money(paid)}</div></div><div className="stat"><div className="statLabel">22(iii)(b) Not paid within Section 15 time</div><div className="statValue">{money(notPaid)}</div></div></section><section className="card" style={{marginTop:16}}><div className="note">Working-paper calculation. Review MSE applicability and statutory due dates before final reporting.</div><div className="tableWrap" style={{marginTop:12}}><table className="table"><thead><tr><th>Sr</th><th>Amount</th><th>Doc Date</th><th>Credit</th><th>Due Date</th><th>Payment</th><th>Status</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.sr}><td>{x.sr}</td><td>{money(x.amount)}</td><td>{fmt(x.doc?new Date(x.doc):null)}</td><td>{x.credit}</td><td>{fmt(x.dueDate)}</td><td>{fmt(x.payDate)}</td><td><span className={"pill "+(x.within?"pillGreen":"pillRed")}>{x.within?"Paid within time":"Review / not within time"}</span></td></tr>):<tr><td colSpan={7}>No processed SAP rows.</td></tr>}</tbody></table></div></section></>;}
